# Generated by Django 4.0.4 on 2022-05-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Photo_Img',
            new_name='Photo_Image',
        ),
    ]
